"use client";

import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useRef } from "react";
import { repoUrl, stats } from "@/lib/data";

const STATS = [
  { label: "test coverage", value: `${stats.coverage}%` },
  { label: "docstring coverage", value: `${stats.docstringCoverage}%` },
  { label: "generated docs", value: stats.generatedDocs },
  { label: "modules", value: stats.modules },
];

export default function CTA() {
  const root = useRef<HTMLDivElement>(null);

  useGSAP(
    () => {
      gsap.registerPlugin(ScrollTrigger);
      gsap.from(".cta-stat", {
        y: 30,
        opacity: 0,
        stagger: 0.1,
        duration: 0.8,
        ease: "power3.out",
        scrollTrigger: { trigger: root.current, start: "top 75%" },
      });
      gsap.from(".cta-core", {
        scale: 0.9,
        opacity: 0,
        duration: 1,
        ease: "power3.out",
        scrollTrigger: { trigger: ".cta-core", start: "top 80%" },
      });
    },
    { scope: root },
  );

  return (
    <section ref={root} className="relative overflow-hidden px-6 pb-20 pt-[12vh]">
      <div className="mx-auto mb-24 grid max-w-4xl grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 md:grid-cols-4">
        {STATS.map((s) => (
          <div key={s.label} className="cta-stat bg-white/[0.02] p-6 text-center">
            <div className="text-3xl font-bold text-gradient md:text-4xl">{s.value}</div>
            <div className="mt-2 font-mono text-[10px] uppercase tracking-widest text-white/40">
              {s.label}
            </div>
          </div>
        ))}
      </div>

      <div className="cta-core relative mx-auto max-w-3xl text-center">
        <div className="pointer-events-none absolute left-1/2 top-1/2 h-[60vmax] w-[60vmax] -translate-x-1/2 -translate-y-1/2 rounded-full opacity-40 blur-[130px]"
          style={{ background: "radial-gradient(circle, rgba(160,107,255,0.4), transparent 60%)" }}
        />
        <h2 className="relative text-balance text-4xl font-bold leading-[1.05] tracking-tight md:text-6xl">
          Make stale docs <span className="text-gradient text-glow">impossible</span>.
        </h2>

        <div className="relative mx-auto mt-10 flex w-fit items-center gap-3 rounded-xl border border-white/10 bg-black/40 px-5 py-3 font-mono text-sm">
          <span className="text-[var(--color-cyan)]">$</span>
          <span className="text-white/85">pip install -e . &amp;&amp; living-docs update</span>
        </div>

        <div className="relative mt-8 flex flex-wrap items-center justify-center gap-4">
          <a
            href={repoUrl}
            target="_blank"
            rel="noreferrer"
            className="group relative overflow-hidden rounded-full bg-white px-7 py-3.5 text-sm font-semibold text-black transition-transform hover:scale-[1.03]"
          >
            <span className="relative z-10">Use this template ↗</span>
          </a>
          <a
            href={`${repoUrl}#readme`}
            target="_blank"
            rel="noreferrer"
            className="rounded-full border border-white/15 px-7 py-3.5 text-sm font-medium text-white/80 transition hover:border-white/40 hover:text-white"
          >
            Read the docs
          </a>
        </div>
      </div>

      <footer className="relative mx-auto mt-28 flex max-w-5xl flex-col items-center justify-between gap-4 border-t border-white/10 pt-8 font-mono text-xs text-white/35 md:flex-row">
        <span>living-docs · self-updating documentation engine</span>
        <span>generated by AST · rendered to Markdown · verified by CI</span>
      </footer>
    </section>
  );
}
